<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createVectorFromDocumentList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vR2V0IGlucHV0cyBmcm9tIHRoZSBwaXBlbGluZS4KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJz
b3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFbXSBpbnB1dExpc3QgPSBJRGF0YVV0aWwu
Z2V0SURhdGFBcnJheSggcGlwZWxpbmVDdXJzb3IsICJpbnB1dExpc3QiICk7CnBpcGVsaW5lQ3Vy
c29yLmRlc3Ryb3koKTsKClZlY3RvciByZXR1cm5WYWwgPSBudWxsOwoKLy9DaGVjayB0aGUgaW5w
dXRzLgppZiAoaW5wdXRMaXN0ID09IG51bGwgfHwgaW5wdXRMaXN0Lmxlbmd0aCA8IDEpCnsKCS8v
Tm8gaW5wdXQgbGlzdCAtIG1ha2UgYW4gZW1wdHkgVmVjdG9yLgoJcmV0dXJuVmFsID0gbmV3IFZl
Y3RvcigpOwp9CmVsc2UKewoJLy9DcmVhdGUgdGhlIFZlY3Rvci4KCXJldHVyblZhbCA9IG5ldyBW
ZWN0b3IoKTsKCgkvL0xvb3AgdGhyb3VnaCB0aGUgaW5wdXQgbGlzdCwgYWRkaW5nIGVhY2ggcmVj
b3JkIHRvIHRoZSBWZWN0b3IuCglJRGF0YUN1cnNvciBpbnB1dExpc3RDdXJzb3IgPSBudWxsOwoJ
Zm9yIChpbnQgaSA9IDA7IGkgPCBpbnB1dExpc3QubGVuZ3RoOyBpKyspCgl7CgkJcmV0dXJuVmFs
LmFkZChpbnB1dExpc3RbaV0pOwoJfQp9CgovL1JldHVybiB0aGUgVmVjdG9yLgpJRGF0YUN1cnNv
ciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQo
cGlwZWxpbmVDdXJzb3JfMSwgInZlY3RvciIsIHJldHVyblZhbCk7CnBpcGVsaW5lQ3Vyc29yXzEu
ZGVzdHJveSgpOwo=</value>
</Values>
