<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createTempFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgpTdHJpbmcgcHJlZml4
ID0gbnVsbDsKU3RyaW5nIHN1ZmZpeCA9IG51bGw7CkZpbGUgZm9sZGVyID0gbnVsbDsKCmlmIChj
dXJzb3IuZmlyc3QoInByZWZpeCIpKQp7CiAgcHJlZml4ID0gKFN0cmluZyljdXJzb3IuZ2V0VmFs
dWUoKTsKfQoKaWYgKHByZWZpeCA9PSBudWxsIHx8IHByZWZpeC5sZW5ndGgoKSA8IDMpCnsKICB0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiVGhlIGZpZWxkICdwcmVmaXgnIHNob3VsZCBiZSBh
dGxlYXN0IDMgY2hhcmFjdGVycyBsb25nIik7Cn0KCmlmIChjdXJzb3IuZmlyc3QoInN1ZmZpeCIp
KQp7CiAgc3VmZml4ID0gKFN0cmluZyljdXJzb3IuZ2V0VmFsdWUoKTsKfQoKaWYgKGN1cnNvci5m
aXJzdCgiZm9sZGVyIikpCnsKICBmb2xkZXIgPSBuZXcgRmlsZSgoU3RyaW5nKWN1cnNvci5nZXRW
YWx1ZSgpKTsKfQp0cnkKewogIC8vIENyZWF0ZSB0aGUgZmlsZSBmcm9tIHRoZSBpbnB1dCBwYXJh
bXRlcnMgCiAgRmlsZSB0ZW1wRmlsZSA9IEZpbGUuY3JlYXRlVGVtcEZpbGUocHJlZml4LCBzdWZm
aXgsIGZvbGRlcik7CiAgLy9TYXZlIHRoZSBmdWxsIGZpbGUgcGF0aCB0byBvdXRwdXQgcGFyYW1l
dGVycy4KICBzZXRWYWx1ZShjdXJzb3IsICJ0ZW1wRmlsZSIsIHRlbXBGaWxlLmdldENhbm9uaWNh
bFBhdGgoKSk7CiAgc2V0VmFsdWUoY3Vyc29yLCAidGVtcFdyaXRlciIsIG5ldyBCdWZmZXJlZFdy
aXRlcihuZXcgRmlsZVdyaXRlcih0ZW1wRmlsZSkpKTsKfQpjYXRjaCAoSU9FeGNlcHRpb24gaW9l
KQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oaW9lKTsKfQpmaW5hbGx5CnsKICBjdXJz
b3IuZGVzdHJveSgpOwp9</value>
</Values>
