<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringToDate</value>
  <value name="encodeutf8">true</value>
  <value name="body">CUlEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOyAKCglTdHJpbmcgZGF0
ZUZvcm1hdCA9ICJ5eXl5LU1NLWRkIEhIOm1tOnNzIjsgCglTdHJpbmcgZGF0ZVN0cmluZyA9IG51
bGw7IAoKCWlmKGN1cnNvci5maXJzdCgiZGF0ZVN0cmluZyIpKSAKCXsgCgkJZGF0ZVN0cmluZyA9
IChTdHJpbmcpY3Vyc29yLmdldFZhbHVlKCk7IAoJfSAKCWVsc2UgCgl7IAoJCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKCJNaXNzaW5nIGlucHV0ICdkYXRlJyIpOyAKCX0gCgoJaWYgKGN1cnNv
ci5maXJzdCgicGF0dGVybiIpKSAKCXsgCgkJZGF0ZUZvcm1hdCA9IChTdHJpbmcpY3Vyc29yLmdl
dFZhbHVlKCk7IAoJfSAKCgoJU2ltcGxlRGF0ZUZvcm1hdCBzZGYgPSBuZXcgU2ltcGxlRGF0ZUZv
cm1hdChkYXRlRm9ybWF0KTsgCglEYXRlIGRhdGU7IAoJdHJ5IAoJeyAKCQlkYXRlID0gc2RmLnBh
cnNlKGRhdGVTdHJpbmcpOyAKCQlJRGF0YVV0aWwucHV0KGN1cnNvciwgImRhdGUiLCBkYXRlKTsg
Cgl9IAoJY2F0Y2ggKFBhcnNlRXhjZXB0aW9uIHBlKSAKCXsgCgkJdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oIkRhdGUgJyIgKyBkYXRlU3RyaW5nICsgCgkJCSInIGNhbm5vdCBiZSBwYXJzZWQg
dXNpbmcgdGhlIGZvcm1hdCAnIiArIGRhdGVGb3JtYXQgKyAiJyIpOyAKCX0gCglmaW5hbGx5IAoJ
eyAKCQljdXJzb3IuZGVzdHJveSgpOyAKCX0=</value>
</Values>
