<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">rename</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCUNoYW5uZWxTZnRwIGMgPSAoQ2hhbm5lbFNmdHApSURhdGFVdGlsLmdldCggcGlwZWxp
bmVDdXJzb3IsICJDaGFubmVsU2Z0cCIgKTsKCVN0cmluZwlyZW1vdGVGaWxlT2xkID0gSURhdGFV
dGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJyZW1vdGVGaWxlT2xkIiApOwoJU3RyaW5n
CXJlbW90ZUZpbGVOZXcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInJl
bW90ZUZpbGVOZXciICk7CgkKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoKU3RyaW5nIHN0YXR1
cyA9IG51bGw7CnRyeSB7CgkKICAgIAljLnJlbmFtZShyZW1vdGVGaWxlT2xkLCByZW1vdGVGaWxl
TmV3KTsKCXN0YXR1cyA9ICJPSyI7CiAgICAKfQpjYXRjaCAoRXhjZXB0aW9uIGUpIHsKCiAgICAg
ICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiVW5hYmxlIHRvIHJlbmFtZSBmaWxlOiAiK3Jl
bW90ZUZpbGVPbGQrIiAiK2UudG9TdHJpbmcoKSk7CiAgICAvLyBzdGF0dXMgPSAiVW5hYmxlIHRv
IHJlbmFtZSBmaWxlOiAiK3JlbW90ZUZpbGVPbGQrIiAiK2UudG9TcmluZygpOwp9CgpJRGF0YUN1
cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CiAgICAgSURhdGFV
dGlsLnB1dChwaXBlbGluZUN1cnNvcl8xLCJzdGF0dXMiLHN0YXR1cyk7CnBpcGVsaW5lQ3Vyc29y
XzEuZGVzdHJveSgpOw==</value>
</Values>
