<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeFileWriter</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzIApJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVs
aW5lLmdldEN1cnNvcigpOwpTdHJpbmcgCXN0ckZpbGVDb250ZW50ID0gbnVsbDsKCi8vT3V0cHV0
IFZhcmlhYmxlcyAKU3RyaW5nIHN1Y2Nlc3NGbGFnID0gImZhbHNlIjsKQnVmZmVyZWRXcml0ZXIg
ZmlsZVdyaXRlciA9IG51bGw7CgovLyBDaGVjayB0byBzZWUgaWYgdGhlIGZpbGVXcml0ZXIgb2Jq
ZWN0IGlzIGluIHRoZSBwaXBlbGluZQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImZpbGVXcml0ZXIi
KSkKewkKCS8vZ2V0IHRoZSBCdWZmZXJlZFdyaXRlciBzdHJlYW0gb3V0IG9mIHRoZSBwaXBlbGlu
ZQkJCQkJCglmaWxlV3JpdGVyID0gKEJ1ZmZlcmVkV3JpdGVyKSBpZGNQaXBlbGluZS5nZXRWYWx1
ZSgpOwp9Ci8vaWYgaXQgaXMgbm90IGluIHRoZSBwaXBlbGluZSwgdGhlbiBoYW5kbGUgdGhlIGVy
cm9yCmVsc2UKewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVycm9yOiAgZmlsZVdyaXRl
ciBvYmplY3QgaXMgbm90IGluIHRoZSBwaXBlbGluZSEiKTsKfQovLyBDaGVjayB0byBzZWUgaWYg
dGhlIGZpbGVDb250ZW50IG9iamVjdCBpcyBpbiB0aGUgcGlwZWxpbmUKaWYgKGlkY1BpcGVsaW5l
LmZpcnN0KCJmaWxlQ29udGVudCIpKQkKewoJCS8vZ2V0IHRoZSBmaWxlQ29udGVudCBvdXQgb2Yg
dGhlIHBpcGVsaW5lCQkJCQkJCgkJc3RyRmlsZUNvbnRlbnQgPSAoU3RyaW5nKSBpZGNQaXBlbGlu
ZS5nZXRWYWx1ZSgpOwp9Ci8vaWYgaXQgaXMgbm90IGluIHRoZSBwaXBlbGluZSwgdGhlbiBoYW5k
bGUgdGhlIGVycm9yCmVsc2UKewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVycm9yOiAg
ZmlsZUNvbnRlbnQgb2JqZWN0IGlzIG5vdCBpbiB0aGUgcGlwZWxpbmUhISIpOwp9CgovLyBUcnkg
dG8gd3JpdGUgdG8gdGhlIEJ1ZmZlcmVkV3JpdGVyIG9iamVjdC4gIEhhbmRsZSB0aGUgZXhjZXB0
aW9uIGlmIGl0IGZhaWxzLgp0cnkKewoJZmlsZVdyaXRlci53cml0ZShzdHJGaWxlQ29udGVudCk7
CgoJLy9TZXQgdGhlIHN1Y2Nlc3MgZmxhZyBiZWNhdXNlIHRoZSBzZXJ2aWNlIHdhcyBzdWNjZXNz
ZnVsCglzdWNjZXNzRmxhZyA9ICJ0cnVlIjsKfQpjYXRjaCAoRXhjZXB0aW9uIGUpCnsKCS8vU2V0
IHRoZSBzdWNjZXNzIGZsYWcgYmVjYXVzZSB0aGUgc2VydmljZSBmYWlsZWQKCXN1Y2Nlc3NGbGFn
ID0gImZhbHNlIjsKfQoKLy9yZW1vdmUgYW55IG90aGVyIHN1Y2Nlc3NGbGFncyBmcm9tIHBpcGxp
bmUKaWYoaWRjUGlwZWxpbmUuZmlyc3QoInN1Y2Nlc3NGbGFnIikpCnsKCQlpZGNQaXBlbGluZS5k
ZWxldGUoKTsKfQovL2luc2VydCB0aGUgc3VjY2Vzc0ZsYWcgaW50byB0aGUgcGlwZWxpbmUKaWRj
UGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOwkKCi8vQWx3
YXlzIGRlc3Ryb3kgY3Vyc3VycyB0aGF0IHlvdSBjcmVhdGVkCmlkY1BpcGVsaW5lLmRlc3Ryb3ko
KTsJCg==</value>
</Values>
