<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteObjectFromBucket</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7CglBbWF6b25TMyBjb25uID0gKEFtYXpvblMzKSBJRGF0YVV0aWwuZ2V0KCBwaXBlbGlu
ZUN1cnNvciwgImNvbm4iICk7CglTdHJpbmcJYnVja2V0TmFtZSA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAiYnVja2V0TmFtZSIgKTsKCVN0cmluZyBmaWxla2V5ID0gSURh
dGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJmaWxla2V5Iik7CglTdHJpbmcgc3Rh
dHVzID0gImZhbHNlIjsKCXRyeQoJewoJCWNvbm4uZGVsZXRlT2JqZWN0KGJ1Y2tldE5hbWUsIGZp
bGVrZXkpOwoJCXN0YXR1cyA9ICJ0cnVlIjsKCX0KCWNhdGNoKEV4Y2VwdGlvbiBlKQoJewogICAg
ICAgICAgICAgICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS50b1N0cmluZygpKTsKCX0J
CQoKLy8gcGlwZWxpbmUKCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAic3RhdHVzIiwg
c3RhdHVzICk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTs=</value>
</Values>
