<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringTableToDocumentList</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoKCURlc2NyaXB0aW9uOglTdHJpbmcgVGFibGUgdG8gRG9jdW1lbnQgTGlzdCBVdGlsaXR5CglB
dXRob3I6CQkJQ3Jvd2UgQ2hpemVrCglEYXRlOgkJCTA4LzI1LzA0CglEZXRhaWxzOgkJVGFrZXMg
YSBTdHJpbmcgVGFibGUgKFN0cmluZ1tdW10pIGFuZCBjb252ZXJ0cyBpdCB0byBhIGRvY3VtZW50
IGxpc3QuCiovCgovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVs
aW5lLmdldEN1cnNvcigpOwpTdHJpbmdbXVtdCXN0cmluZ1RhYmxlID0gSURhdGFVdGlsLmdldFN0
cmluZ1RhYmxlKCBwaXBlbGluZUN1cnNvciwgInN0cmluZ1RhYmxlIiApOwoKLy8gbWFrZSBzdXJl
IHdlIGhhdmUgaW5wdXQgYW5kIHRoZSB0YWJsZSBoYXMgYXQgbGVhc3Qgb25lIGVudHJ5CmlmIChz
dHJpbmdUYWJsZSAhPSBudWxsICYmIHN0cmluZ1RhYmxlLmxlbmd0aCA+IDApIHsKCSAKCVN0cmlu
ZyB2YWx1ZSA9ICJ2YWx1ZSI7CglJRGF0YVtdIGRvY3VtZW50TGlzdCA9IG51bGw7Cglkb2N1bWVu
dExpc3QgPSBuZXcgSURhdGFbc3RyaW5nVGFibGUubGVuZ3RoXTsKCUlEYXRhQ3Vyc29yIGRvY3Vt
ZW50Q3Vyc29yID0gbnVsbDsKCWZvciAoaW50IGk9MDsgaTxzdHJpbmdUYWJsZS5sZW5ndGg7IGkr
KykgewoJCS8vIGFkZCBhbGwgdmFsdWVzIHRvIHJlY29yZCBpbiB0aGUgbGlzdCwgYXNzaWduIGZp
ZWxkIG5hbWUgb2YgdmFsdWUgcGx1cyBvcmRlciBpbiBsaXN0CgkJZG9jdW1lbnRMaXN0W2ldID0g
SURhdGFGYWN0b3J5LmNyZWF0ZSgpOwoJCWRvY3VtZW50Q3Vyc29yID0gZG9jdW1lbnRMaXN0W2ld
LmdldEN1cnNvcigpOwoJCWZvciAoaW50IGo9MDsgajxzdHJpbmdUYWJsZVtpXS5sZW5ndGg7IGor
KykgewoJCQlJRGF0YVV0aWwucHV0KCBkb2N1bWVudEN1cnNvciwgdmFsdWUraiwgc3RyaW5nVGFi
bGVbaV1bal0gKTsKCQl9CgkJZG9jdW1lbnRDdXJzb3IuZGVzdHJveSgpOwoJfQoJSURhdGFVdGls
LnB1dCggcGlwZWxpbmVDdXJzb3IsICJkb2N1bWVudExpc3QiLCBkb2N1bWVudExpc3QgKTsKCXBp
cGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKfSBlbHNlIHsKCXBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3ko
KTsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJVbmFibGUgdG8gZ2VuZXJhdGUgZG9jdW1l
bnQgbGlzdCBmcm9tIHN0cmluZyB0YWJsZTogSW5wdXQgcGFyYW1ldGVyICdzdHJpbmdUYWJsZScg
bXVzdCBjb250YWluIGEgdGFibGUgd2l0aCBhdCBsZWFzdCAxIHJvdy4iKTsKfQ==</value>
</Values>
