<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">EBCDICToAscii</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCVN0cmlu
ZwlpblN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5TdHJp
bmciICk7CglTdHJpbmcJdHJpbSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAidHJpbSIgKTsKClN0cmluZyBvdXRTdHJpbmcgPSAiIjsKaW50IGogPSAwOwoKd2hpbGUgKGog
PCBpblN0cmluZy5sZW5ndGgoKSkKewoJb3V0U3RyaW5nID0gb3V0U3RyaW5nICsgdHJhbnNsYXRl
U3RyaW5nKGluU3RyaW5nLnN1YnN0cmluZyhqLGorMikpOwoJaiA9IGorMjsKfQoKaWYgKCh0cmlt
IT0gbnVsbCkgJiYgKHRyaW0uZXF1YWxzKCJ0cnVlIikpKQoJb3V0U3RyaW5nID0gb3V0U3RyaW5n
LnRyaW0oKTsKCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAib3V0U3RyaW5nIiwgb3V0
U3RyaW5nKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
