<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getEntryDN</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCklEYXRhIGxkYXBTZWFyY2hSZXN1bHRzID0gSURhdGFVdGlsLmdldElEYXRhKCBwaXBl
bGluZUN1cnNvciwgImxkYXBTZWFyY2hSZXN1bHRzIiApOwoKaWYgKGxkYXBTZWFyY2hSZXN1bHRz
ICE9IG51bGwpCnsKIElEYXRhQ3Vyc29yIGxkYXBTZWFyY2hSZXN1bHRzQ3Vyc29yID0gbGRhcFNl
YXJjaFJlc3VsdHMuZ2V0Q3Vyc29yKCk7CiBpZiAoIGxkYXBTZWFyY2hSZXN1bHRzQ3Vyc29yLmZp
cnN0KCkgKQogewoJU3RyaW5nIGtleSA9IGxkYXBTZWFyY2hSZXN1bHRzQ3Vyc29yLmdldEtleSgp
OwoKCUlEYXRhIHVpZCA9IElEYXRhVXRpbC5nZXRJRGF0YShsZGFwU2VhcmNoUmVzdWx0c0N1cnNv
cixsZGFwU2VhcmNoUmVzdWx0c0N1cnNvci5nZXRLZXkoKSk7CglJRGF0YUN1cnNvciB1aWRDdXJz
b3IgPSB1aWQuZ2V0Q3Vyc29yKCk7CglpZih1aWRDdXJzb3IuZmlyc3QoKSkKCXsKCQkvL3BpcGVs
aW5lQ3Vyc29yLmluc2VydEFmdGVyKCJteUtleSIsdWlkQ3Vyc29yLmdldEtleSgpKTsKCQlwaXBl
bGluZUN1cnNvci5pbnNlcnRBZnRlcigiZW50cnlETiIsdWlkQ3Vyc29yLmdldFZhbHVlKCkpOwoJ
fQoJdWlkQ3Vyc29yLmRlc3Ryb3koKTsJCQogIH0KIGxkYXBTZWFyY2hSZXN1bHRzQ3Vyc29yLmRl
c3Ryb3koKTsKfQoKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwo=</value>
</Values>
