<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">reload</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioKU2VydmljZSAJcmVsb2FkKCkKCklucHV0OiAgCQpSZXR1cm5z
OgkKQ29tbWVudHM6CVVzZXMgREJDb25uZWN0aW9uTWFuYWdlci4KCkRhdGU6ICAgICAgICAgICAg
ICAgICAgICAgIAlEZXNjcmlwdGlvbiBvZiB0aGUgY2hhbmdlLgoxMi8xNi8wMglUb255IEZvbHR6
CQlDcmVhdGlvbi4KKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8gCiAKQ29ubmVjdGlvbiAJCQljb25uZWN0
aW9uCSA9IG51bGw7CkFTREJDb25uZWN0aW9uTWFuYWdlciBwb29sTWFuYWdlciAgPSBudWxsOwpT
dHJpbmcgCQkJCWFjdGlvbiAgCSA9IG51bGw7ClN0cmluZwkJCQlwcm9wZXJ0aWVzRmlsZSA9IG51
bGw7CgpJRGF0YUN1cnNvciBjdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKaWYgKGN1cnNv
ci5maXJzdCgicHJvcGVydGllc0ZpbGUiKSkgewoJcHJvcGVydGllc0ZpbGUgPSAoU3RyaW5nKSBj
dXJzb3IuZ2V0VmFsdWUoKTsKfQoKdHJ5CXsKCWFjdGlvbiA9ICJnZXR0aW5nIHBvb2xNYW5hZ2Vy
IjsKCXBvb2xNYW5hZ2VyID0gQVNEQkNvbm5lY3Rpb25NYW5hZ2VyLmdldEluc3RhbmNlKCk7CgoJ
aWYgKHBvb2xNYW5hZ2VyID09IG51bGwpIHsKCQlEZWJ1Zy5sb2coMCwgImdldENvbm5lY3Rpb246
IEVycm9yID0gUG9vbE1hbmFnZXIgd2FzIG51bGw6ICIgKyBwb29sTWFuYWdlciApOwoJfQoJZWxz
ZSB7CgkJYWN0aW9uID0gInJlbG9hZGluZyB0aGUgcG9vbE1hbmFnZXIiOwoJCWlmICgocHJvcGVy
dGllc0ZpbGUgIT0gbnVsbCkgJiYgKHByb3BlcnRpZXNGaWxlICE9ICIiKSkgewoJCQlwb29sTWFu
YWdlci5yZWxvYWQocHJvcGVydGllc0ZpbGUpOwoJCX0KCQllbHNlIHsKCQkJcG9vbE1hbmFnZXIu
cmVsb2FkKCk7CgkJfSAKCX0KCWN1cnNvci5pbnNlcnRBZnRlcigic3RhdHVzIiwgIlN1Y2Nlc3Nm
dWwiKTsKfQpjYXRjaCAoRXhjZXB0aW9uIGUpIHsKCURlYnVnLmxvZygwLCAicmV0dXJuQ29ubmVj
dGlvbjogRXJyb3IgPSAiICsgZS50b1N0cmluZygpICsgIjsiICsgYWN0aW9uKTsKCXRyeQl7CgkJ
VmFsdWVzIGVycm9yID0gbmV3IFZhbHVlcygpOwogICAgICAgCWVycm9yLnB1dCgibXNnVHlwZSIs
ICJlcnJvciIpOwoJCWVycm9yLnB1dCgibWVzc2FnZSIsICJFeGNlcHRpb24gd2l0aGluIHJldHVy
bkNvbm5lY3Rpb24sIHdoaWxlICIrYWN0aW9uKyIuICIgKyBlLnRvU3RyaW5nKCkpOyAgICAgCgkJ
Y3Vyc29yLmluc2VydEFmdGVyKCJlcnJvciIsIGVycm9yKTsKCX0KCWNhdGNoIChFeGNlcHRpb24g
eCkJewoJfQp9</value>
</Values>
