<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">multiConcat</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKLy8gQmFzZWQgb24gdGhlIG11bHRpQ29uY2F0IGxvZ2ljIGZyb20gdGhlIFBT
VXRpbGl0aWVzIHBhY2thZ2UKCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7CglTdHJpbmcJaW5TdHIxID0gY2hlY2tOdWxsKElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5TdHIxIiApKTsKCVN0cmluZwlpblN0cjIgPSBjaGVja051
bGwoSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpblN0cjIiICkpOwoJU3Ry
aW5nCWluU3RyMyA9IGNoZWNrTnVsbChJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNv
ciwgImluU3RyMyIgKSk7CglTdHJpbmcJaW5TdHI0ID0gY2hlY2tOdWxsKElEYXRhVXRpbC5nZXRT
dHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5TdHI0IiApKTsKCVN0cmluZwlpblN0cjUgPSBjaGVj
a051bGwoSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpblN0cjUiICkpOwoJ
U3RyaW5nCWluU3RyNiA9IGNoZWNrTnVsbChJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgImluU3RyNiIgKSk7CglTdHJpbmcJaW5TdHI3ID0gY2hlY2tOdWxsKElEYXRhVXRpbC5n
ZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5TdHI3IiApKTsKCVN0cmluZwlpblN0cjggPSBj
aGVja051bGwoSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpblN0cjgiICkp
OwoJU3RyaW5nCWluU3RyOSA9IGNoZWNrTnVsbChJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGlu
ZUN1cnNvciwgImluU3RyOSIgKSk7CglTdHJpbmcJaW5TdHIxMCA9IGNoZWNrTnVsbChJRGF0YVV0
aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImluU3RyMTAiICkpOwoKClN0cmluZyBvdXRT
dHIgPSBpblN0cjEgKyBpblN0cjIgKyBpblN0cjMgKyBpblN0cjQgKyBpblN0cjUgKyBpblN0cjYg
KyBpblN0cjcgKyBpblN0cjggKyBpblN0cjkgKyBpblN0cjEwOwpJRGF0YVV0aWwucHV0KCBwaXBl
bGluZUN1cnNvciwgIm91dFN0ciIsIG91dFN0ciApOwoKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
Owo=</value>
</Values>
