<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">insertRecordIntoHashtable</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vR2V0IHZhbHVlcyBmcm9tIHBpcGVsaW5lLgpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9
IHBpcGVsaW5lLmdldEN1cnNvcigpOwpJRGF0YSBpbnB1dFJlY29yZCA9IElEYXRhVXRpbC5nZXRJ
RGF0YShwaXBlbGluZUN1cnNvciwgImlucHV0UmVjb3JkIik7ClN0cmluZyBrZXlGaWVsZCA9IElE
YXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJzb3IsICJrZXlGaWVsZCIpOwpPYmplY3QgaGFz
aHRhYmxlID0gSURhdGFVdGlsLmdldChwaXBlbGluZUN1cnNvciwgImhhc2h0YWJsZSIpOwpwaXBl
bGluZUN1cnNvci5kZXN0cm95KCk7CgovL0NoZWNrIGlucHV0cy4KSGFzaHRhYmxlIG91dHB1dEhh
c2ggPSBudWxsOwppZiAoaGFzaHRhYmxlID09IG51bGwgfHwgIShoYXNodGFibGUgaW5zdGFuY2Vv
ZiBIYXNodGFibGUpKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbiAoIlRoZSBoYXNodGFi
bGUgaW5wdXQgbXVzdCBiZSBhIEphdmEgaGFzaHRhYmxlLiIpOwp9CmVsc2UKewoJb3V0cHV0SGFz
aCA9IChIYXNodGFibGUpIGhhc2h0YWJsZTsKfQppZiAoa2V5RmllbGQgPT0gbnVsbCB8fCBrZXlG
aWVsZC50cmltKCkuZXF1YWxzKCIiKSkKewoJLy9ObyBrZXkgZmllbGQgdG8gdXNlLiBJbnZhbGlk
IGlucHV0LgoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24gKCJObyBrZXkgZmllbGQgdmFsdWUg
cHJvdmlkZWQgdG8gaW5zZXJ0IGludG8gSGFzaHRhYmxlIik7Cn0KaWYgKGlucHV0UmVjb3JkID09
IG51bGwpCnsKCS8vTm8gaW5wdXQgcmVjb3JkIC0ganVzdCByZXR1cm4gdGhlIG9yaWdpbmFsIGhh
c2h0YWJsZS4KfQplbHNlCnsKCS8vSW5zZXJ0IHRoZSB2YWx1ZS4KCUlEYXRhQ3Vyc29yIGlucHV0
TGlzdEN1cnNvciA9IGlucHV0UmVjb3JkLmdldEN1cnNvcigpOwoJU3RyaW5nIGtleVZhbCA9IElE
YXRhVXRpbC5nZXRTdHJpbmcoaW5wdXRMaXN0Q3Vyc29yLCBrZXlGaWVsZCk7CglpZiAoa2V5VmFs
ID09IG51bGwpCgl7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24gKCJUaGUga2V5IHZhbHVl
IGZpZWxkIGRpZCBub3QgZXhpc3QgaW4gdGhlIGlucHV0IHJlY29yZC4iKTsKCX0KCWlmIChvdXRw
dXRIYXNoLmNvbnRhaW5zS2V5KGtleVZhbCkpCgl7CgkJLy9UaGlzIGlzIGEgZHVwbGljYXRlLiBE
byBub3RoaW5nLgoJfQoJZWxzZQoJewoJCW91dHB1dEhhc2gucHV0KGtleVZhbCwgaW5wdXRSZWNv
cmQpOwoJfQp9CgovL1B1dCBvdXRwdXQgdmFsdWVzIGluIHRoZSBwaXBlbGluZS4KSURhdGFDdXJz
b3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpJRGF0YVV0aWwucHV0
KHBpcGVsaW5lQ3Vyc29yXzEsICJoYXNodGFibGUiLCBvdXRwdXRIYXNoKTsKcGlwZWxpbmVDdXJz
b3JfMS5kZXN0cm95KCk7Cg==</value>
</Values>
