<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">lpwd</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCUNoYW5uZWxTZnRwIGMgPSAoQ2hhbm5lbFNmdHApSURhdGFVdGlsLmdldCggcGlwZWxp
bmVDdXJzb3IsICJDaGFubmVsU2Z0cCIgKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwpTdHJp
bmcgc3RhdHVzID0gbnVsbDsKU3RyaW5nIGxwd2QgPSBudWxsOwp0cnkgewogICAgbHB3ZCA9IGMu
bHB3ZCgpOwogICAgc3RhdHVzID0gIk9LIjsKfQpjYXRjaCAoRXhjZXB0aW9uIGUpIHsKICAgIC8v
IHN0YXR1cyA9IGUudG9TdHJpbmcoKTsKICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUu
dG9TdHJpbmcoKSk7Cn0KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsKICAgIElEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3JfMSwic3RhdHVzIixz
dGF0dXMpOwogICAgSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvcl8xLCJscHdkIixscHdkKTsK
cGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7</value>
</Values>
