<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getAllSystemProperties</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqClJldHJpZXZl
cyBhIGxpc3Qgb2Ygc3lzdGVtIHByb3BlcnRpZXMvc2V0dGluZ3MuICBUaGVzZSBpbmNsdWRlIGph
dmEgc2V0dGluZ3MsIGFzIHdlbGwKYXMgd2ViTWV0aG9kcyBzZXJ2ZXIgc2V0dGluZ3MuCkNyZWF0
ZWQ6ICAyLzIwLzIwMDIgIC0gVG9ueSBGb2x0egoqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKiovClByb3BlcnRpZXMgcHJvcGVydGllcyA9IFN5c3RlbS5nZXRQ
cm9wZXJ0aWVzKCk7CkVudW1lcmF0aW9uIHByb3BFbnVtID0gcHJvcGVydGllcy5wcm9wZXJ0eU5h
bWVzKCk7ClN0cmluZyBrZXkgPSAiIjsKU3RyaW5nIHZhbHVlID0iIjsKClZhbHVlcyBvdXRwdXQg
PSBuZXcgVmFsdWVzKCk7CgovL0RlYnVnLmxvZygwLCAiXG5TeXN0ZW0gUHJvcGVydGllcyBcbiAt
LS0tLS0tLS0tLS0tLS0iICsgcHJvcGVydGllcy50b1N0cmluZygpKTsKd2hpbGUgKHByb3BFbnVt
Lmhhc01vcmVFbGVtZW50cygpKSB7CglrZXkgPSAoU3RyaW5nKSBwcm9wRW51bS5uZXh0RWxlbWVu
dCgpOwoJdmFsdWUgPSBwcm9wZXJ0aWVzLmdldFByb3BlcnR5KGtleSk7Ci8vCURlYnVnLmxvZygw
LCBrZXkgKyAiID0gIiArIHZhbHVlKTsKCW91dHB1dC5wdXQoa2V5LCB2YWx1ZSk7Cn0KCklEYXRh
Q3Vyc29yIGN1cnNvciAJPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKY3Vyc29yLmxhc3QoKTsKY3Vy
c29yLmluc2VydEFmdGVyKCJwcm9wZXJ0aWVzIixvdXRwdXQpOw==</value>
</Values>
