<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">closeFileWriter</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzIApCdWZmZXJlZFdyaXRlciBmaWxlV3JpdGVyID0gbnVs
bDsKSURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCQkJCi8v
T3V0cHV0IFZhcmlhYmxlcwpTdHJpbmcgc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOwoKLy8gQ2hlY2sg
dG8gc2VlIGlmIHRoZSBmaWxlV3JpdGVyIG9iamVjdCBpcyBpbiB0aGUgcGlwZWxpbmUKaWYgKGlk
Y1BpcGVsaW5lLmZpcnN0KCJmaWxlV3JpdGVyIikpCnsJCgkvL2dldCB0aGUgQnVmZmVyZWRXcml0
ZXIgc3RyZWFtIG91dCBvZiB0aGUgcGlwZWxpbmUJCQkJCQoJZmlsZVdyaXRlciA9IChCdWZmZXJl
ZFdyaXRlcikgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKfQovL2lmIGl0IGlzIG5vdCBpbiB0aGUg
cGlwZWxpbmUsIHRoZW4gaGFuZGxlIHRoZSBlcnJvcgplbHNlCnsKCXN1Y2Nlc3NGbGFnID0gImZh
bHNlIjsJCgoJLy9pbnNlcnQgdGhlIHN1Y2Nlc3NGbGFnIGludG8gdGhlIHBpcGVsaW5lCglpZGNQ
aXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7CgoJLy9BbHdh
eXMgZGVzdHJveSBjdXJzdXJzIHRoYXQgeW91IGNyZWF0ZWQKCWlkY1BpcGVsaW5lLmRlc3Ryb3ko
KTsJCgkKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJFcnJvciBleGVjdXRpbmcgbHhrc2hh
cmVkLmlvLnV0aWxzOmNsb3NlRmlsZVdyaXRlcjogUmVxdWlyZWQgcGFyYW1ldGVyICdmaWxlV3Jp
dGVyJyBtaXNzaW5nLiIpOwp9CgovLyBUcnkgdG8gZmx1c2ggdGhlIGZpbGVXcml0ZXIgb2JqZWN0
LiAgSGFuZGxlIHRoZSBleGNlcHRpb24gaWYgaXQgZmFpbHMuCnRyeQkJCQp7CglmaWxlV3JpdGVy
LmNsb3NlKCk7CglzdWNjZXNzRmxhZyA9ICJ0cnVlIjsJCQkJCQkKfQpjYXRjaCAoRXhjZXB0aW9u
IGUpCnsKCS8vU2V0IHRoZSBzdWNjZXNzIGZsYWcgYmVjYXVzZSB0aGUgc2VydmljZSBmYWlsZWQK
CXN1Y2Nlc3NGbGFnID0gImZhbHNlIjsKCS8vUHJpbnQgdGhlIGV4Y2VwdGlvbiBvdXQgdG8gc3Rh
bmRhcmQgb3V0cHV0CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVycm9yIGV4ZWN1dGlu
ZyBseGtzaGFyZWQuaW8udXRpbHM6Y2xvc2VGaWxlV3JpdGVyOiIgKyBlLnRvU3RyaW5nKCkpOwkK
fQoKCS8vcmVtb3ZlIGFueSBvdGhlciBzdWNjZXNzRmxhZ3MgZnJvbSBwaXBsaW5lCmlmKGlkY1Bp
cGVsaW5lLmZpcnN0KCJzdWNjZXNzRmxhZyIpKQp7CgkJaWRjUGlwZWxpbmUuZGVsZXRlKCk7Cn0K
Ci8vaW5zZXJ0IHRoZSBzdWNjZXNzRmxhZyBpbnRvIHRoZSBwaXBlbGluZQppZGNQaXBlbGluZS5p
bnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7CgovL0Fsd2F5cyBkZXN0cm95
IGN1cnNvcnMgdGhhdCB5b3UgY3JlYXRlZAppZGNQaXBlbGluZS5kZXN0cm95KCk7Cg==</value>
</Values>
