<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">logout</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCUNoYW5uZWxTZnRwIGMgPSAoQ2hhbm5lbFNmdHApSURhdGFVdGlsLmdldCggcGlwZWxp
bmVDdXJzb3IsICJDaGFubmVsU2Z0cCIgKTsKCVNlc3Npb24Jc2Vzc2lvbiA9IChTZXNzaW9uKSBJ
RGF0YVV0aWwuZ2V0KCBwaXBlbGluZUN1cnNvciwgIlNlc3Npb25GYWN0b3J5IiApOwpwaXBlbGlu
ZUN1cnNvci5kZXN0cm95KCk7CgpTdHJpbmcgc3RhdHVzID0gbnVsbDsKCnRyeSB7CiAgICBjLnF1
aXQoKTsKICAgIHNlc3Npb24uZGlzY29ubmVjdCgpOwogICAgc3RhdHVzID0gIk9LIjsKfSAKY2F0
Y2ggKEV4Y2VwdGlvbiBleGMpIHsKICAgIAogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24o
IlVuYWJsZSB0byBkaXNjb25uZWN0IGZyb20gRlRQIHNlcnZlci4gIiArIGV4Yy50b1N0cmluZygp
KTsKICAgIC8vIHN0YXR1cyA9ICJVbmFibGUgdG8gZGlzY29ubmVjdCBmcm9tIEZUUCBzZXJ2ZXIu
ICIgKyBleGMudG9TdHJpbmcoKTsKfQovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1
cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vy
c29yXzEsICJzdGF0dXMiLCBzdGF0dXMgKTsKcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7</value>
</Values>
