<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">invokeAndCatchErrors</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioKU2VydmljZSAJaW52b2tlQW5kQ2F0Y2hFcnJvcnMoKQoKSW5w
dXQ6ICAJc2VydmljZSAJCT0gVGhlIHNlcnZpY2UgbmFtZSB1c2VkIHRvIGludm9rZSB0aGUgc2Vy
dmljZQoJCQluZXdUaHJlYWQJCT0gQm9vbGVhbiBmbGFnOiB0cnVlIGlmIGZvciBhIHRocmVhZGVk
IHByb2Nlc3MKClJldHVybnM6CWludm9rZUVycm9yCQk9IGVycm9yLCBpZiBuZWVkZWQKCQoqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqLwoJU3RyaW5nIHNlcnZpY2VUb0ludm9rZSA9IGluLmdldFN0cmluZygi
c2VydmljZVRvSW52b2tlIik7CglTdHJpbmcgbmV3VGhyZWFkICAgICAgID0gaW4uZ2V0U3RyaW5n
KCJuZXdUaHJlYWQiKTsKCglTdHJpbmcgdXNlciAgID0gIkFkbWluaXN0cmF0b3IiOyAKCVN0cmlu
ZyBpbnRmY2UgPSAiIjsKCVN0cmluZyBzcnYgICAgPSAiIjsKIAoJaWYgKG5ld1RocmVhZCA9PSBu
dWxsKSB7CgkJbmV3VGhyZWFkID0gImZhbHNlIjsKCX0KCgl0cnkgewoJCWlmIChuZXdUaHJlYWQu
ZXF1YWxzKCJmYWxzZSIpKSB7CgkJCW91dCA9IGRvSW52b2tlKCBOU05hbWUuY3JlYXRlKHNlcnZp
Y2VUb0ludm9rZSksIGluKTsKCQl9CgkJZWxzZSB7CQoJCQlpbnQgaW5kZXggID0gc2VydmljZVRv
SW52b2tlLmluZGV4T2YoIjoiKTsKCQkJaW50IGxlbmd0aCA9IHNlcnZpY2VUb0ludm9rZS5sZW5n
dGgoKTsKCQkJc3J2ICAgID0gc2VydmljZVRvSW52b2tlLnN1YnN0cmluZyhpbmRleCArIDEsIGxl
bmd0aCk7CgkJCWludGZjZSA9IHNlcnZpY2VUb0ludm9rZS5zdWJzdHJpbmcoMCwgaW5kZXgpOwoJ
CQlzcnYgICAgPSBzcnYudHJpbSgpOwoJCQlpbnRmY2UgPSBpbnRmY2UudHJpbSgpOwoJCQlkb1Ro
cmVhZEludm9rZShpbnRmY2UsIHNydiwgaW4pOwoJCX0KCX0KICAgIGNhdGNoKEV4Y2VwdGlvbiBl
KSB7CgkJb3V0LnB1dCgiaW52b2tlRXJyb3IiLCBlLnRvU3RyaW5nKCkpOwoJCW91dC5wdXQoImVy
cm9yTWVzc2FnZSIsIGUuZ2V0TG9jYWxpemVkTWVzc2FnZSgpKTsKCX0=</value>
</Values>
