<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createStrFromStrList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gU3Jpbml2YXMgQWt1bGEgLSB0byByZWFkIHRoZSBzdHJpbmcgYXJyYXkgaW50byBhIGNvbW1h
IHNlcGFyYXRlZCBzdHJpbmcgZm9yIFNRTCBpbmNsYXVzZQovLyBwaXBlbGluZQpJRGF0YUN1cnNv
ciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJU3RyaW5nW10gaW5MaXN0
ID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KCBwaXBlbGluZUN1cnNvciwgImluTGlzdCIgKTsK
CWlmKGluTGlzdCAhPSBudWxsKQoJewoJU3RyaW5nIG91dFN0ciA9ICIiOwoJU3RyaW5nQnVpbGRl
ciBhclRvc3RyID0gbmV3IFN0cmluZ0J1aWxkZXIoKTsKCWZvcihpbnQgaT0wOyBpPGluTGlzdC5s
ZW5ndGg7IGkrKykKCXsKCQlpbkxpc3RbaV0gPSAiJyIraW5MaXN0W2ldLnRyaW0oKSsiJyI7CgkJ
Ly9pbkxpc3RbaV0gPSAiJyIraW5MaXN0W2ldKyInIjsKCQlpZihpICE9MCkKCQl7CgkJCWFyVG9z
dHIuYXBwZW5kKCIsIik7CgkJCWFyVG9zdHIuYXBwZW5kKGluTGlzdFtpXSk7CgkJfQoJCWVsc2UK
CQl7CgkJCWFyVG9zdHIuYXBwZW5kKGluTGlzdFtpXSk7CgkJfQoJfQoJcGlwZWxpbmVDdXJzb3Iu
aW5zZXJ0QWZ0ZXIoIm91dFN0ciIsYXJUb3N0ci50b1N0cmluZygpKTsKCX0KCnBpcGVsaW5lQ3Vy
c29yLmRlc3Ryb3koKTsKCgo=</value>
</Values>
