<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getStreamContent</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklucHV0U3RyZWFtIGlz
ID0gbnVsbDsKCi8vR2V0IHRoZSBpbnB1dCBzdHJlYW0gZnJvbSB0aGUgcGlwZWxpbmUuCmlmIChj
dXJzb3IuZmlyc3QoImlucHV0U3RyZWFtIikpCnsKICBpcyA9IChJbnB1dFN0cmVhbSljdXJzb3Iu
Z2V0VmFsdWUoKTsgIAp9CgppZiAoaXMgPT0gbnVsbCkKewogIHRocm93IG5ldyBTZXJ2aWNlRXhj
ZXB0aW9uKCJNaXNzaW5nIGlucHV0ICdpbnB1dFN0cmVhbSciKTsKfQoKdHJ5CnsKICAvL1JlYWQg
ZnJvbSB0aGUgc3RyZWFtIGFuZCBjcmVhdGUgYSBieXRlIGFycmF5IG9yIGEgc3RvcmFnZSByZWZl
cmVuY2UgZnJvbSBpdC4KICAvKiAKICAgT2JqZWN0IG9iamVjdCA9IHN0cmVhbVRvQnl0ZXNPclJl
c2VydmF0aW9uKGlzKTsKCiAgLy9JZiB0aGUgY3JlYXRlZCBvYmplY3QgaXMgYSBieXRlIGFycmF5
CiAgaWYgKG9iamVjdCBpbnN0YW5jZW9mIGJ5dGVbXSkKICB7CiAgICBzZXRWYWx1ZShjdXJzb3Is
ICJieXRlcyIsIG9iamVjdCk7CiAgICBzZXRWYWx1ZShjdXJzb3IsICJ0eXBlIiwgImJ5dGVBcnJh
eSIpOwogIH0KICAvL0lmIHRoZSBjcmVhdGVkIG9iamVjdCBpcyBhIHN0b3JhZ2UgcmVmZXJlbmNl
CiAgZWxzZSBpZiAob2JqZWN0IGluc3RhbmNlb2YgUmVzZXJ2YXRpb24pCiAgewogICAgc2V0VmFs
dWUoY3Vyc29yLCAic3RvcmFnZVJlZiIsIG9iamVjdCk7CiAgICBzZXRWYWx1ZShjdXJzb3IsICJ0
eXBlIiwgInRzcGFjZSIpOwogIH0KICAqLwp9CmNhdGNoIChFeGNlcHRpb24gZSkKewogIHRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9CmZpbmFsbHkKewogIGN1cnNvci5kZXN0cm95KCk7
Cn0=</value>
</Values>
