<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createAccessRefreshFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVjdXJzb3I9cGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQogDQpTdHJp
bmcgYWNjZXNzVG9rZW49SURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZWN1cnNvciwgImFjY2Vz
c1Rva2VuIik7DQpTdHJpbmcgcmVmcmVzaFRva2VuPUlEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxp
bmVjdXJzb3IsICJyZWZyZXNoVG9rZW4iKTsNCnBpcGVsaW5lY3Vyc29yLmRlc3Ryb3koKTsNClN0
cmluZyBzZXJ2ZXJSb290ID0gU3lzdGVtLmdldFByb3BlcnR5KCJ1c2VyLmRpciIpOyAvL2dldCBz
ZXJ2ZXIgcm9vdA0KDQoNCgkJSlNPTk9iamVjdCBvYmogPSBuZXcgSlNPTk9iamVjdCgpOw0KCQlv
YmoucHV0KCJhY2Nlc3NUb2tlbiIsIGFjY2Vzc1Rva2VuKTsNCgkJb2JqLnB1dCgicmVmcmVzaFRv
a2VuIiwgcmVmcmVzaFRva2VuKTsNCgkJDQoJCQ0KCQl0cnkgKEZpbGVXcml0ZXIgZmlsZSA9IG5l
dyBGaWxlV3JpdGVyKHNlcnZlclJvb3QrIi9wYWNrYWdlcy9MWEtEMzY1U2hhcmVkL2NvbmZpZy9E
MzY1X0FjY2Vzc1JlZnJlc2hUb2tlbi5qc29uIikpIHsNCgkJDQoJCSAgICBmaWxlLndyaXRlKG9i
ai50b0pTT05TdHJpbmcoKSk7DQoJCSAgICBmaWxlLmZsdXNoKCk7DQoJCQ0KCQl9IGNhdGNoIChJ
T0V4Y2VwdGlvbiBlKSB7DQoJCSAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLnRvU3Ry
aW5nKCkpOyANCgkJfQ0KCQ==</value>
</Values>
