<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">doThreadInvoke</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1
cnNvcigpOwpTdHJpbmcgc2VydmljZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGlu
ZUN1cnNvcl8xLCAic2VydmljZU5hbWUiICk7CklEYXRhIHNlcnZpY2VJbnB1dHMgPSBJRGF0YVV0
aWwuZ2V0SURhdGEoIHBpcGVsaW5lQ3Vyc29yXzEsICJzZXJ2aWNlSW5wdXRzIiApOwpwaXBlbGlu
ZUN1cnNvcl8xLmRlc3Ryb3koKTsKCnRyeQp7CglOU05hbWUgZnVuY3Rpb25hbFNlcnZlclNlcnZp
Y2VOYW1lID0gTlNOYW1lLmNyZWF0ZShzZXJ2aWNlTmFtZSk7CglTZXJ2aWNlLmRvVGhyZWFkSW52
b2tlKGZ1bmN0aW9uYWxTZXJ2ZXJTZXJ2aWNlTmFtZSwgc2VydmljZUlucHV0cyk7Cn0KY2F0Y2gg
KEV4Y2VwdGlvbiBlKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiVW5hYmxlIHRvIGlu
dm9rZSBzZXJ2aWNlIGR1ZSB0bzogIiArIGUpOwp9</value>
</Values>
