<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ErrorString</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCVN0cmluZwlJblN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vy
c29yLCAiSW5TdHJpbmciICk7CgoKdHJ5CnsKU3RyaW5nIEtleVdvcmQgPSAiICI7CgppbnQgaSA9
IEluU3RyaW5nLmluZGV4T2YoImludmFsaWQgbnVtYmVyIik7CmludCBqPSAgSW5TdHJpbmcuaW5k
ZXhPZigiTWF0Y2ggRXJyb3IiKTsKaW50IGsgPSBJblN0cmluZy5pbmRleE9mKCJDbGVhbnNlIEVy
cm9yIik7CmludCBsID0gSW5TdHJpbmcuaW5kZXhPZigiVHJpbGxpdW0iKTsKIAogCmlmKGk+PTAp
CntLZXlXb3JkID0gImludmFsaWQgbnVtYmVyIjsKfQplbHNlIGlmKGo+PTApCntLZXlXb3JkID0g
Ik1hdGNoIEVycm9yIjsKfQplbHNlIGlmKGs+PTApCntLZXlXb3JkID0gIkNsZWFuc2UgRXJyb3Ii
Owp9CmVsc2UgaWYobD49MCkKe0tleVdvcmQgPSAiVHJpbGxpdW0iOwp9CgoKcGlwZWxpbmVDdXJz
b3IuZGVzdHJveSgpOwovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0g
cGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJL
ZXlXb3JkIiwgS2V5V29yZCApOwpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsKCn0KCmNhdGNo
IChFeGNlcHRpb24gZSkKe30=</value>
</Values>
