<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readLine</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgppZiAoY3Vyc29yLmZp
cnN0KCJyZWFkZXIiKSkKewogIC8vR2V0IHRoZSByZWFkZXIgZnJvbSB0aGUgcGlwZWxpbmUKICBC
dWZmZXJlZFJlYWRlciByZWFkZXIgPSAoQnVmZmVyZWRSZWFkZXIpY3Vyc29yLmdldFZhbHVlKCk7
CiAgU3RyaW5nIGxpbmUgPSBudWxsOwogIHRyeQogIHsKICAgIC8vIFJlYWQgYSBsaW5lIG9mIGRh
dGEgZnJvbSB0aGUgcmVhZGVyLgogICAgbGluZSA9IHJlYWRlci5yZWFkTGluZSgpOwogIH0KICBj
YXRjaCAoSU9FeGNlcHRpb24gaW9lKQogIHsKICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KGlvZSk7CiAgfQoKICBpZiAoY3Vyc29yLmZpcnN0KCJsaW5lIikpCiAgewogICAgY3Vyc29yLnNl
dFZhbHVlKGxpbmUpOwogIH0KICBlbHNlCiAgewogICAgY3Vyc29yLmluc2VydEFmdGVyKCJsaW5l
IiwgbGluZSk7CiAgfQp9CgpjdXJzb3IuZGVzdHJveSgpOyA=</value>
</Values>
