<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSessionID</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioKU2VydmljZSAJZ2V0U2Vzc2lvbklEKCkKCklucHV0OiAgCQoK
UmV0dXJuczoJCgpDb21tZW50czoJCkRhdGU6ICAgICAgICAgICAgICAgICAgICAgIAlEZXNjcmlw
dGlvbiBvZiB0aGUgY2hhbmdlLgowOS8xMi8wMCAgIAlUb255IEZvbHR6ICAgICAgSW5pdGlhbCBj
cmVhdGlvbgoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqLyAKCQpTZXNzaW9uIHNlc3Npb25JbnN0YW5jZSA9
IGdldFNlc3Npb24oKTsKClN0cmluZyBzZXNzaW9uSUQgPSBzZXNzaW9uSW5zdGFuY2UuZ2V0U2Vz
c2lvbklEKCk7CiAKb3V0LnB1dCgic2Vzc2lvbklEIiwgc2Vzc2lvbklEKTs=</value>
</Values>
