<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">documentValuesToString</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKU3Ry
aW5nIG91dFN0cmluZyA9IG51bGw7ClN0cmluZyBkZWxpbWl0ZXIgPSBudWxsOwoJCglpZiAoaWRj
LmZpcnN0KCJkZWxpbWl0ZXIiKSkKCQlkZWxpbWl0ZXIgPSAoU3RyaW5nKWlkYy5nZXRWYWx1ZSgp
OwoJZWxzZQoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJubyBkZWxpbWl0ZXIiKTsKCglp
ZiAoaWRjLmZpcnN0KCJkb2N1bWVudCIpKQoJaWRjID0gKChJRGF0YSlpZGMuZ2V0VmFsdWUoKSku
Z2V0Q3Vyc29yKCk7CgoJaWRjLmZpcnN0KCk7CgkKCWlmIChpZGMuZ2V0VmFsdWUoKSBpbnN0YW5j
ZW9mIFN0cmluZykKCW91dFN0cmluZyA9ICgoaWRjLmdldFZhbHVlKCk9PW51bGwpPygiIik6KChT
dHJpbmcpaWRjLmdldFZhbHVlKCkpKTsKCgl3aGlsZShpZGMubmV4dCgpKSAKCXsKCQkvL291dFN0
cmluZyA9IG91dFN0cmluZyArIGRlbGltaXRlciArIGlkYy5nZXRLZXkoKTsKCQlpZiAoaWRjLmdl
dFZhbHVlKCkgaW5zdGFuY2VvZiBTdHJpbmcpCgkJb3V0U3RyaW5nID0gb3V0U3RyaW5nICsgZGVs
aW1pdGVyICsgKChpZGMuZ2V0VmFsdWUoKT09bnVsbCk/KCIiKTooKFN0cmluZylpZGMuZ2V0VmFs
dWUoKSkpOwoJfQoKCWlkYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKCWlmIChpZGMuZmlyc3Qo
Im91dFN0cmluZyIpKQoJCWlkYy5zZXRWYWx1ZShvdXRTdHJpbmcpOwoJZWxzZQoJCWlkYy5pbnNl
cnRBZnRlcigib3V0U3RyaW5nIiwgb3V0U3RyaW5nKTsKCQppZGMuZGVzdHJveSgpOwo=</value>
</Values>
