<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">toProperCase</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5n
CWluU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpblN0cmlu
ZyIgKTsKCnRyeQp7CglpblN0cmluZyA9IChpblN0cmluZy5zdWJzdHJpbmcoMCwgMSkpLnRvVXBw
ZXJDYXNlKCkJKyAoaW5TdHJpbmcuc3Vic3RyaW5nKDEpKS50b0xvd2VyQ2FzZSgpOwoJaW50IHNw
YWNlUG9zID0gMDsKCWludCBzdGFydFBvcyA9IDA7CgoJd2hpbGUgKGluU3RyaW5nLmxlbmd0aCgp
ID4gMSAmJiAoc3BhY2VQb3MgPSBpblN0cmluZy5pbmRleE9mKCIgIiwgc3RhcnRQb3MpKSA+IC0x
ICkKCXsKCQlpblN0cmluZyA9IGluU3RyaW5nLnN1YnN0cmluZygwLCBzcGFjZVBvcyArIDEpIAoJ
CQkJCSsgKGluU3RyaW5nLnN1YnN0cmluZyhzcGFjZVBvcyArIDEsIHNwYWNlUG9zICsgMikpLnRv
VXBwZXJDYXNlKCkKCQkJCQkrIGluU3RyaW5nLnN1YnN0cmluZyhzcGFjZVBvcysyKTsKCQlzdGFy
dFBvcyA9IHNwYWNlUG9zICsgMjsKCX0KfQpjYXRjaCAoRXhjZXB0aW9uIHgpCnsKCVN5c3RlbS5v
dXQucHJpbnRsbigiRXJyb3Igd2hpbGUgcGFyc2luZyBzdHJpbmciKTsKCWluU3RyaW5nID0gSURh
dGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpblN0cmluZyIgKTsKfQoKSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJvdXRTdHJpbmciLCBpblN0cmluZyk7CnBpcGVsaW5l
Q3Vyc29yLmRlc3Ryb3koKTsK</value>
</Values>
