<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">checkFileSize</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gR2V0IHBpcGVsaW5lIHZhcmlhYmxlcy4KU3RyaW5nIHN0ckZpbGVOYW1lID0gaW4uZ2V0U3Ry
aW5nKCJmaWxlTmFtZSIpOwpTdHJpbmcgc3RyRmlsZURpcmVjdG9yeSA9IGluLmdldFN0cmluZygi
ZmlsZURpcmVjdG9yeSIpOwoKLy8gR2V0IHN5c3RlbSBmaWxlIHNlcGFyYXRvci4KU3RyaW5nIHN0
ckZpbGVTZXBhcmF0b3IgPSBTeXN0ZW0uZ2V0UHJvcGVydHkoImZpbGUuc2VwYXJhdG9yIiwgIi8i
KTsKCi8vIERldGVybWluZSBsYXN0IGNoYXJhY3RlciBvZiBkaXJlY3RvcnkgdmFyaWFibGUuClN0
cmluZyBzdHJGaWxlID0gbnVsbDsKaWYgKCBzdHJGaWxlRGlyZWN0b3J5LmVuZHNXaXRoKHN0ckZp
bGVTZXBhcmF0b3IpICkgewoJc3RyRmlsZSA9IHN0ckZpbGVEaXJlY3RvcnkuY29uY2F0KHN0ckZp
bGVOYW1lKTsKfSBlbHNlIHsKCXN0ckZpbGUgPSBzdHJGaWxlRGlyZWN0b3J5LmNvbmNhdChzdHJG
aWxlU2VwYXJhdG9yLmNvbmNhdChzdHJGaWxlTmFtZSkpOwp9CgovLyBHZXQgZmlsZSBkZXNjcmlw
dG9yLgpGaWxlIGZpbGUgPSBuZXcgRmlsZShzdHJGaWxlKTsKCi8vIEdldCBmaWxlIHNpemUuCmxv
bmcgZmlsZVNpemUgPSBmaWxlLmxlbmd0aCgpOwoKLy8gU2V0IHBpcGVsaW5lIHZhcmlhYmxlLgpv
dXQucHV0KCAiZmlsZVNpemUiLCBMb25nLnRvU3RyaW5nKCBmaWxlU2l6ZSApICk7IAo=</value>
</Values>
