<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">appendToFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWZpbGVuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJmaWxlTmFtZSIgKTsNCglTdHJpbmcJbWVzc2FnZSA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAiZGF0YSIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsN
Cg0KQnVmZmVyZWRXcml0ZXIgYncgPSBudWxsOw0KDQp0cnkgDQp7DQoJYncgPSBuZXcgQnVmZmVy
ZWRXcml0ZXIobmV3IEZpbGVXcml0ZXIoZmlsZW5hbWUsIHRydWUpKTsNCglidy53cml0ZShtZXNz
YWdlKTsNCgkvL2J3Lm5ld0xpbmUoKTsNCglidy5mbHVzaCgpOw0KfSANCmNhdGNoIChJT0V4Y2Vw
dGlvbiBpb2UpIA0Kew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGlvZS50b1N0cmluZygp
KTsNCn0gDQpmaW5hbGx5IA0KeyAgICAgICAgICAgICAgICAgICAgICAgLy8gYWx3YXlzIGNsb3Nl
IHRoZSBmaWxlDQoJaWYgKGJ3ICE9IG51bGwpIA0KCXRyeSANCgl7DQoJCWJ3LmNsb3NlKCk7DQoJ
fSANCgljYXRjaCAoSU9FeGNlcHRpb24gaW9lMikgDQoJew0KCQl0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbihpb2UyLnRvU3RyaW5nKCkpOw0KCX0NCn0gLy8gZW5kIHRyeS9jYXRjaC9maW5hbGx5
DQoJ</value>
</Values>
