<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">checkStringPattern</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBpblN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5TdHJp
bmciICk7DQpTdHJpbmcgc3RyaW5nUGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVs
aW5lQ3Vyc29yLCAic3RyaW5nUGF0dGVybiIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsN
Cg0KU3RyaW5nIHN0YXR1cz0iZmFsc2UiOw0KDQppZiAoaW5TdHJpbmcuY29udGFpbnMoc3RyaW5n
UGF0dGVybikpDQp7DQoJc3RhdHVzPSJ0cnVlIjsNCn0NCg0KDQpJRGF0YUN1cnNvciBwaXBlbGlu
ZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGlu
ZUN1cnNvcl8xLCAic3RhdHVzIiwgc3RhdHVzKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgp
Ow==</value>
</Values>
