<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">isBucketExists</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1
cnNvcigpOw0KCUFtYXpvblMzIGNvbm4gPSAoQW1hem9uUzMpIElEYXRhVXRpbC5nZXQoIHBpcGVs
aW5lQ3Vyc29yLCAiY29ubiIgKTsNCglTdHJpbmcJYnVja2V0TmFtZSA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiYnVja2V0TmFtZSIgKTsNCglib29sZWFuIGJ1Y2tldEV4
aXN0cyA9IGZhbHNlOw0KCXRyeQ0KCXsNCgkJYnVja2V0RXhpc3RzPWNvbm4uZG9lc0J1Y2tldEV4
aXN0KGJ1Y2tldE5hbWUpOw0KCX0NCgljYXRjaChFeGNlcHRpb24gZSkNCgl7DQogICAgICAgICAg
ICAgICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS50b1N0cmluZygpKTsNCgl9CQkNCg0K
Ly8gcGlwZWxpbmUNCg0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJidWNrZXRFeGlz
dHMiLCBidWNrZXRFeGlzdHMgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCgk=</value>
</Values>
