<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeNonAlphaNumericChars</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yIAkJPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nIAlpblN0
cmluZyAJCT0gIiI7ClN0cmluZyAJb3V0U3RyaW5nIAkJPSAiIjsKaW50IAlpbkxlbmd0aCAJCT0g
MDsKY2hhciAJdGhpc0NoYXIJIAk9ICdhJzsKCmlmIChjdXJzb3IubGFzdCgiaW5wdXRTdHJpbmci
KSkgewoJaW5TdHJpbmcgPSAoU3RyaW5nKSBjdXJzb3IuZ2V0VmFsdWUoKTsKfQplbHNlIHsKCXJl
dHVybjsKfQoKaW5MZW5ndGggPSBpblN0cmluZy5sZW5ndGgoKTsKCmZvciAoaW50IGk9MDsgaTxp
bkxlbmd0aDsgaSsrKSB7Cgl0aGlzQ2hhciA9IGluU3RyaW5nLmNoYXJBdChpKTsKCWlmIChDaGFy
YWN0ZXIuaXNMZXR0ZXJPckRpZ2l0KHRoaXNDaGFyKSkgewoJCW91dFN0cmluZyA9IG91dFN0cmlu
Zy5jb25jYXQoU3RyaW5nLnZhbHVlT2YodGhpc0NoYXIpKTsKCX0KfQoKY3Vyc29yLmxhc3QoKTsK
Y3Vyc29yLmluc2VydEFmdGVyKCJvdXRwdXRTdHJpbmciLCBvdXRTdHJpbmcpOwo=</value>
</Values>
