<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createLargeDocDirs</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBmaWxlU2Vw
ID0gU3lzdGVtLmdldFByb3BlcnR5KCJmaWxlLnNlcGFyYXRvciIpOwpTdHJpbmcgaW5zdGFsbERp
cj0gU3lzdGVtLmdldFByb3BlcnR5KCJ1c2VyLmRpciIpOwpTdHJpbmdbXSBwYWNrYWdlcyA9IG51
bGw7ClN0cmluZyBTb3VyY2VkaXIgPSBudWxsOwpTdHJpbmcgV0lQZGlyID0gbnVsbDsKU3RyaW5n
IEFyY2hpdmVkaXIgPSBudWxsOwpTdHJpbmcgT3V0cHV0ZGlyID0gbnVsbDsKU3RyaW5nIHJvb3RE
aXIgPSBudWxsOwoKaWYgKGN1cnNvci5maXJzdCgicGFja2FnZXMiKSkKewogIHBhY2thZ2VzID0g
KFN0cmluZ1tdKSBjdXJzb3IuZ2V0VmFsdWUoKTsKfQoKaWYgKHBhY2thZ2VzICE9IG51bGwgJiYg
cGFja2FnZXMubGVuZ3RoID4gMCkgCnsKCWZvciAoaW50IGkgPSAwOyBpIDwgcGFja2FnZXMubGVu
Z3RoOyBpKyspIAoJewoJCXJvb3REaXIgPSAoaW5zdGFsbERpcitmaWxlU2VwKyJwYWNrYWdlcyIr
ZmlsZVNlcCtwYWNrYWdlc1tpXStmaWxlU2VwKyJwdWIiK2ZpbGVTZXArIkxESCIpOwoJCVNvdXJj
ZWRpciA9IChyb290RGlyK2ZpbGVTZXArIklucHV0IitmaWxlU2VwKTsKCQlXSVBkaXIgPSAocm9v
dERpcitmaWxlU2VwKyJXSVAiK2ZpbGVTZXApOwoJCUFyY2hpdmVkaXIgPSAocm9vdERpcitmaWxl
U2VwKyJBcmNoaXZlIitmaWxlU2VwKTsKCQlPdXRwdXRkaXIgPSAocm9vdERpcitmaWxlU2VwKyJP
dXRwdXQiK2ZpbGVTZXApOwoKCQlGaWxlIHJvb3QgPSBuZXcgRmlsZSAocm9vdERpcik7CgkJRmls
ZSBhID0gbmV3IEZpbGUgKFNvdXJjZWRpcik7CgkJRmlsZSBiID0gbmV3IEZpbGUgKFdJUGRpcik7
CgkJRmlsZSBjID0gbmV3IEZpbGUgKEFyY2hpdmVkaXIpOwoJCUZpbGUgZCA9IG5ldyBGaWxlIChP
dXRwdXRkaXIpOwoKCQlpZiAoIXJvb3QuZXhpc3RzKCkpCgkJewoJCQlyb290Lm1rZGlycygpOwoJ
CX0KCQlpZiAoIWEuZXhpc3RzKCkpIAoJCXsKCQkgICAgYS5ta2RpcnMoKTsKCQl9CgkJaWYgKCFi
LmV4aXN0cygpKSAKCQl7CgkJICAgIGIubWtkaXJzKCk7CgkJfQoJCWlmICghYy5leGlzdHMoKSkg
CgkJewoJCSAgICBjLm1rZGlycygpOwoJCX0KCQlpZiAoIWQuZXhpc3RzKCkpIAoJCXsKCQkgICAg
ZC5ta2RpcnMoKTsKCQl9CgoJfQp9CmN1cnNvci5kZXN0cm95KCk7Cg==</value>
</Values>
