<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pullB2BCoreFromException</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBpbnB1dE1l
c3NhZ2UgPSAiIjsKU3RyaW5nIG91dHB1dE1lc3NhZ2UgPSAiIjsKCmlmIChjdXJzb3IubGFzdCgi
aW5wdXRNZXNzYWdlIikpIHsKCWlucHV0TWVzc2FnZSA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1
ZSgpOwoJaW5wdXRNZXNzYWdlID0gaW5wdXRNZXNzYWdlLnRyaW0oKTsKfQplbHNlIHsKCURlYnVn
LmxvZygwLCAicHVsbEIyQkNvcmVGcm9tRXhjZXB0aW9uOiBpbnB1dCBtaXNzaW5nLiIpOwp9Cgpp
ZiAoaW5wdXRNZXNzYWdlLnN0YXJ0c1dpdGgoIltCMkJDT1JFIikpIHsKCWludCByaWdodEJyYWNr
ZXRJbmRleCA9IGlucHV0TWVzc2FnZS5pbmRleE9mKCJdIik7CglvdXRwdXRNZXNzYWdlID0gaW5w
dXRNZXNzYWdlLnN1YnN0cmluZyhyaWdodEJyYWNrZXRJbmRleCArIDEpOwoJb3V0cHV0TWVzc2Fn
ZSA9IG91dHB1dE1lc3NhZ2UudHJpbSgpOwp9CmVsc2UgewoJb3V0cHV0TWVzc2FnZSA9IGlucHV0
TWVzc2FnZTsKfQoKY3Vyc29yLmxhc3QoKTsKY3Vyc29yLmluc2VydEFmdGVyKCJvdXRwdXRNZXNz
YWdlIiwgb3V0cHV0TWVzc2FnZSk7CgovL1tCMkJDT1JFLjAwNjQuOTAwNV0gNTMwIExvZ2luIGlu
Y29ycmVjdC4=</value>
</Values>
