<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">setResponse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgpTdHJpbmcgY29udGVudFR5
cGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgImNvbnRlbnQtdHlwZSIpOwpTdHJpbmcgZmls
ZW5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgImZpbGVuYW1lIik7CmJ5dGVbXSBjb250
ZW50ID0gKGJ5dGVbXSlJRGF0YVV0aWwuZ2V0KGlkYywgImNvbnRlbnQiKTsKCkh0dHBIZWFkZXIg
aGRyID0gU2VydmljZS5nZXRIdHRwUmVzcG9uc2VIZWFkZXIoKFZhbHVlcylwaXBlbGluZSk7Cmlm
KGhkciAhPSBudWxsKSB7CgloZHIuYWRkRmllbGQoIkNvbnRlbnQtVHlwZSIsIGNvbnRlbnRUeXBl
KTsKCWhkci5hZGRGaWVsZCgiQ29udGVudC1EaXNwb3NpdGlvbiIsICJhdHRhY2htZW50OyBmaWxl
bmFtZT1cIiIgKyBmaWxlbmFtZSArICJcIiIpOwovL1N5c3RlbS5vdXQucHJpbnRsbigiYXR0YWNo
bWVudDsgZmlsZW5hbWU9XCIiICsgZmlsZW5hbWUgKyAiXCIiKTsKfSAKZWxzZXsKICAgLy9TeXN0
ZW0ub3V0LnByaW50bG4oIkh0dHAgSGVhZGVyIGlzIG51bGwgISEhISEhISEhISAiKTsKfQpTZXJ2
aWNlLnNldFJlc3BvbnNlKChWYWx1ZXMpcGlwZWxpbmUsIGNvbnRlbnQpOwoKaWRjLmRlc3Ryb3ko
KTs=</value>
</Values>
