<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">dateToJulianDate</value>
  <value name="encodeutf8">true</value>
  <value name="body">CUlEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CglpZGNQaXBl
bGluZS5maXJzdCgieWVhciIpOwoJaW50IGkgPSBJbnRlZ2VyLnBhcnNlSW50KChTdHJpbmcpIGlk
Y1BpcGVsaW5lLmdldFZhbHVlKCkpOyAgCglpZGNQaXBlbGluZS5maXJzdCgibW9udGgiKTsKCVN0
cmluZyBtID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKCWlkY1BpcGVsaW5lLmRl
bGV0ZSgpOwoJaWRjUGlwZWxpbmUuZmlyc3QoImRheSIpOwoJU3RyaW5nIGQgPSAoU3RyaW5nKSBp
ZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwoJaWRjUGlwZWxpbmUuZGVsZXRlKCk7CgoJCWlmIChtLmxl
bmd0aCgpID09IDEpCgkJCW0gPSAiMCIgKyBtOwoKCQlpZiAoZC5sZW5ndGgoKSA9PSAxKQoJCQlk
ID0gIjAiICsgZDsKCglpbnQgaiA9IEludGVnZXIucGFyc2VJbnQobSk7CglpbnQgayA9IEludGVn
ZXIucGFyc2VJbnQoZCk7CgoJICAgICAgICBHcmVnb3JpYW5DYWxlbmRhciBncmVnb3JpYW5jYWxl
bmRhciA9IG5ldyBHcmVnb3JpYW5DYWxlbmRhcihpLCBqIC0gMSwgayk7CiAgICAgICAgU3RyaW5n
IHMgPSBTdHJpbmcudmFsdWVPZihncmVnb3JpYW5jYWxlbmRhci5nZXQoNikpOwogICAgICAgIGlm
KHMubGVuZ3RoKCkgPT0gMSkKICAgICAgICAgICAgcyA9ICIwMCIgKyBzOwogICAgICAgIGVsc2UK
ICAgICAgICBpZihzLmxlbmd0aCgpID09IDIpCiAgICAgICAgICAgIHMgPSAiMCIgKyBzOwogICAg
ICAgIFN0cmluZyBzMSA9IFN0cmluZy52YWx1ZU9mKGkgLSAxOTAwKSArIHM7CgoJCWlmIChzMS5s
ZW5ndGgoKSA8IDYpIHsKCQkJaW50IGRpZmYgPSAoNi1zMS5sZW5ndGgoKSk7CgkJCQlmb3IgKGkg
PSAwOyBpIDwgZGlmZjsgaSsrKSB7CgkJCQkJczEgPSAiMCIgKyBzMTsKCQkJCX0KCQl9CgoJaWRj
UGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoIm1vbnRoIixtKTsKCWlkY1BpcGVsaW5lLmluc2VydEFmdGVy
KCJkYXkiLGQpOwoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImp1bGlhbkRhdGUiLHMxKTs=</value>
</Values>
