<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getServerDomainName_hardcode</value>
  <value name="encodeutf8">true</value>
  <value name="body">Y29tLndtLmFwcC5iMmIuc2VydmVyLlNlcnZlckFQSSBhcGkgPSBuZXcgY29tLndtLmFwcC5iMmIu
c2VydmVyLlNlcnZlckFQSSgpOwpTdHJpbmcgc2VydmVyTmFtZSA9IGFwaS5nZXRTZXJ2ZXJOYW1l
KCk7CgovL0RlYnVnLmxvZygwLCBzZXJ2ZXJOYW1lKTsgCgovLyBQYXJzZSBuYW1lIChpLmUuIHZp
cGVydGVzdC5sZXgubGV4bWFyay5jb20gLT4gdmlwZXJ0ZXN0KQppbnQgZG90U3BvdCA9IHNlcnZl
ck5hbWUuaW5kZXhPZignLicpOwoKaWYgKGRvdFNwb3QgPT0gLTEpIHsgICAvLyBpLmUuIEIyQjMK
CXNlcnZlck5hbWUgPSBzZXJ2ZXJOYW1lICsgIi5sZXgubGV4bWFyay5jb20iOwoJaWYgKHNlcnZl
ck5hbWUgPT0gImIyYnFuYSIpIHsKCQlzZXJ2ZXJOYW1lID0gc2VydmVyTmFtZSArICIubGV4MS5s
ZXhtYXJrLmNvbSI7Cgl9Cn0KCgoKb3V0LnB1dCgic2VydmVyTmFtZSIsIHNlcnZlck5hbWUpOwo=
</value>
</Values>
