<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">nsLookupThisServer</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqClJldHJpZXZl
cyB0aGUgaG9zdG5hbWUgYW5kIElQIGFkZHJlc3Mgb2YgdGhpcyBzZXJ2ZXIgYnkgcGVyZm9taW5n
IGEgVU5JWCAnbnNsb29rdXAnCmNvbW1hbmQuCkNyZWF0ZWQ6ICAyLzIwLzIwMDIgIC0gVG9ueSBG
b2x0egoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovCgpJ
RGF0YUN1cnNvciBjdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nIGhvc3RuYW1l
IAk9ICIiOwpTdHJpbmcgbnNsb29rdXBTdHIgCT0gIiI7ClN0cmluZyB0aGlzTGluZSAJPSAiIjsK
U3RyaW5nIGZ1bGxIb3N0TmFtZSA9ICIiOyAKU3RyaW5nIGlwQWRkcmVzcyAJPSAiIjsKCnRyeSB7
CgkvL0dldCB0aGUgaG9zdG5hbWUKCVByb2Nlc3MgdGhlUHJvY2VzcyA9IFJ1bnRpbWUuZ2V0UnVu
dGltZSgpLmV4ZWMoImhvc3RuYW1lIik7CglJbnB1dFN0cmVhbSBpblN0cmVhbSA9IHRoZVByb2Nl
c3MuZ2V0SW5wdXRTdHJlYW0oKTsKICAgIEJ1ZmZlcmVkUmVhZGVyIGJ1ZmZlcmVkUmVhZGVyID0g
bmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBJbnB1dFN0cmVhbVJlYWRlcihpblN0cmVhbSkpOwkKCWhv
c3RuYW1lID0gYnVmZmVyZWRSZWFkZXIucmVhZExpbmUoKTsKCgkvLyBQZXJmb3JtIG5zbG9va3Vw
IG9uIGhvc3RuYW1lCgl0aGVQcm9jZXNzID0gUnVudGltZS5nZXRSdW50aW1lKCkuZXhlYygibnNs
b29rdXAgIiArIGhvc3RuYW1lKTsKCWluU3RyZWFtID0gdGhlUHJvY2Vzcy5nZXRJbnB1dFN0cmVh
bSgpOwogICAgYnVmZmVyZWRSZWFkZXIgPSBuZXcgQnVmZmVyZWRSZWFkZXIobmV3IElucHV0U3Ry
ZWFtUmVhZGVyKGluU3RyZWFtKSk7CQoKCS8vIFJlYWQgaW4gY29tbWFuZCBvdXRwdXQKCXdoaWxl
KCh0aGlzTGluZSA9IGJ1ZmZlcmVkUmVhZGVyLnJlYWRMaW5lKCkpICE9IG51bGwgKSB7CgkJbnNs
b29rdXBTdHIgPSBuc2xvb2t1cFN0ciArIHRoaXNMaW5lICsgIlxuIjsKCX0KCglpbnQgbmFtZUlu
ZGV4ID0gbnNsb29rdXBTdHIuaW5kZXhPZigiTmFtZToiKTsKCW5zbG9va3VwU3RyID0gbnNsb29r
dXBTdHIuc3Vic3RyaW5nKG5hbWVJbmRleCk7CglTdHJpbmdUb2tlbml6ZXIgdG9rZW5pemVyID0g
bmV3IFN0cmluZ1Rva2VuaXplcihuc2xvb2t1cFN0ciwgIlxuIik7CglTdHJpbmcgbGluZVRva2Vu
ID0gIiI7CgoJd2hpbGUgKHRva2VuaXplci5oYXNNb3JlRWxlbWVudHMoKSkgewoJCWxpbmVUb2tl
biA9IHRva2VuaXplci5uZXh0VG9rZW4oKTsKCQlpZiAobGluZVRva2VuLnN0YXJ0c1dpdGgoIk5h
bWUiKSkgewoJCQlmdWxsSG9zdE5hbWUgPSBsaW5lVG9rZW4uc3Vic3RyaW5nKGxpbmVUb2tlbi5p
bmRleE9mKCI6IikrMSkudHJpbSgpOwoJCX0KCQlpZiAobGluZVRva2VuLnN0YXJ0c1dpdGgoIkFk
ZHJlc3MiKSkgewoJCQlpcEFkZHJlc3MgPSBsaW5lVG9rZW4uc3Vic3RyaW5nKGxpbmVUb2tlbi5p
bmRleE9mKCI6IikrMSkudHJpbSgpOwoJCX0KCX0KCWN1cnNvci5sYXN0KCk7CgljdXJzb3IuaW5z
ZXJ0QWZ0ZXIoImhvc3ROYW1lIiwgZnVsbEhvc3ROYW1lKTsKCWN1cnNvci5pbnNlcnRBZnRlcigi
aXBBZGRyZXNzIiwgaXBBZGRyZXNzKTsKfQpjYXRjaCAoRXhjZXB0aW9uIGUpIHsKLy8JRGVidWcu
bG9nKDAsIGUudG9TdHJpbmcoKSk7CgljdXJzb3IubGFzdCgpOwoJY3Vyc29yLmluc2VydEFmdGVy
KCJlcnJvciIsIGUudG9TdHJpbmcoKSk7Cn0K</value>
</Values>
