<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">returnHashTableValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7CglIYXNodGFibGUJaW5IYXNoVGFibGUgPSAoSGFzaHRhYmxlKSBJRGF0YVV0aWwuZ2V0
KCBwaXBlbGluZUN1cnNvciwgImluSGFzaFRhYmxlIiApOwoJU3RyaW5nCWluS2V5ID0gSURhdGFV
dGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpbktleSIgKTsKcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOwoKU3RyaW5nIG91dFZhbHVlID0gIiI7CnRyeSB7CglvdXRWYWx1ZSA9IGluSGFz
aFRhYmxlLmdldChpbktleSkudG9TdHJpbmcoKTsKCX0KY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7Cglv
dXRWYWx1ZSA9ICIiOwoJfQoKLy8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3Jf
MSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8x
LCAib3V0VmFsdWUiLCBvdXRWYWx1ZSApOwpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsK</value>
</Values>
