<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">streamToString</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRoYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKSW5wdXRTdHJlYW0gaXM9
bnVsbDsKCndoaWxlIChpZGhjLm5leHQoKSApIHsKCWlmICggaWRoYy5nZXRLZXkoKS5lcXVhbHMo
InN0cmVhbSIpICkgewoKCQlpcyA9IChJbnB1dFN0cmVhbSlpZGhjLmdldFZhbHVlKCk7CgoJCWJy
ZWFrOwoJfQp9CgppZiAoaXMgIT0gbnVsbCApIHsKCWJ5dGUgYltdID0gbmV3IGJ5dGVbODE5Ml07
CgoJQnl0ZU91dHB1dEJ1ZmZlciBvdXQgPSBuZXcgQnl0ZU91dHB1dEJ1ZmZlcigpOwoKCWludCBy
ZWFkOwoKCXRyeSB7CgkJd2hpbGUgKCAocmVhZCA9IGlzLnJlYWQoYikpID4gMCApIHsKCgkJCS8v
CVN5c3RlbS5lcnIucHJpbnQoKGNoYXIpcmVhZCk7CgoJCSAgIG91dC53cml0ZShiLCAwLCByZWFk
KTsKCgkJfQoKCQlTdHJpbmcgc3RyaW5nID0gb3V0LnRvU3RyaW5nKCk7CgoJCWlkaGMubGFzdCgp
OwoKCQlpZGhjLmluc2VydEFmdGVyKCJzdHJpbmciLCBzdHJpbmcpOwoKCX0gY2F0Y2ggKCBJT0V4
Y2VwdGlvbiBpb2UgKSB7CgoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGlvZS5nZXRNZXNz
YWdlKCkgKTsKCgl9CgoJaWRoYy5kZXN0cm95KCk7Cn0gZWxzZSB7CgoJdGhyb3cgbmV3IFNlcnZp
Y2VFeGNlcHRpb24oIk5vIGNvbnRlbnQiKTsKfQoK</value>
</Values>
