<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">updateDBConnection</value>
  <value name="encodeutf8">true</value>
  <value name="body">REJDb25uZWN0aW9uIGRiQ29ubmVjdCAgPSBudWxsOwppbnQJICAgcm93cwkJCQk9IDA7ClN0cmlu
ZyBvdXRwdXQgCQkJPSAiIjsKU3RyaW5nIHF1ZXJ5ICAgCQkJPSAiIjsKU3RyaW5nIGVycm9yTGlz
dAkJPSAiIjsKCklEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKY3Vy
c29yLmZpcnN0KCJzcWxTdGF0ZW1lbnQiKTsKcXVlcnkgPSAoU3RyaW5nKSBjdXJzb3IuZ2V0VmFs
dWUoKTsKCmlmIChjdXJzb3IuZmlyc3QoImRiQ29ubmVjdGlvbiIpKSB7CglkYkNvbm5lY3QgPSAo
REJDb25uZWN0aW9uKSBjdXJzb3IuZ2V0VmFsdWUoKTsKfQplbHNlIHsKCUV4Y2VwdGlvbiBleCA9
IG5ldyBFeGNlcHRpb24oIklucHV0IHBhcmFtZXRlciBEQkNvbm5lY3Rpb24gbm90IGZvdW5kLiIp
OwoJZXJyb3JMaXN0ID0gZXJyb3JMaXN0ICsgZXgudG9TdHJpbmcoKSArICJcbiI7Cn0KCnRyeSB7
CglkYkNvbm5lY3Quc2V0QXV0b0NvbW1pdCh0cnVlKTsgCglyb3dzID0gZGJDb25uZWN0LmV4ZWN1
dGVVcGRhdGUocXVlcnkpOwoJY3Vyc29yLmluc2VydEFmdGVyKCJyb3dzVXBkYXRlZCIsIEludGVn
ZXIudG9TdHJpbmcocm93cykpOwp9CmNhdGNoIChFeGNlcHRpb24gZSkgewoJRGVidWcubG9nKDAs
ICJFeGNlcHRpb24gPSAiICsgZS50b1N0cmluZygpKTsKCURlYnVnLmxvZygwLCAiUXVlcnkgPSAi
ICsgcXVlcnkpOwoJZXJyb3JMaXN0ID0gZXJyb3JMaXN0ICsgZS50b1N0cmluZygpICsgIlxuIjsK
fQoKaWYgKGVycm9yTGlzdCAhPSAiIikgewoJY3Vyc29yLmluc2VydEFmdGVyKCJlcnJvcnMiLCBl
cnJvckxpc3QpOwp9</value>
</Values>
