<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringFormatter</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyogKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKgpUaGlz
IHNlcnZpY2UgdGFrZXMgYSBzdHJpbmcgYW5kIGNvbnZlcnRzIGl0IGludG8gYSBmb3JtYXQgYWNj
ZXB0ZWQgYnkgU2llYmVsIApQaWNrbGlzdHMuIFRoZSBmaXJzdCBsZXR0ZXIgb2YgZXZlcnkgd29y
ZCBpbiB0aGUgc3RyaW5nIHNob3VsZCBiZSBjYXBpdGFsIGFuZAp0aGUgcmVtYWluZWQgc2hvdWxk
IGJlIHNtYWxsIGNhc2UuCioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqICovCgovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOwoJU3RyaW5nCWluU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmlu
ZyggcGlwZWxpbmVDdXJzb3IsICJpblN0cmluZyIgKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
OwoKClN0cmluZyBvdXRTdHJpbmcgPSAiIjsgCgppZihpblN0cmluZyAhPSBudWxsKXsKCglTdHJp
bmcgdG9rZW4gPSBuZXcgU3RyaW5nKCk7CglTdHJpbmcgdGVtcHRva2VuID0gbmV3IFN0cmluZygp
OwoKCVN0cmluZ1Rva2VuaXplciBzdGtuenIgPSBuZXcgU3RyaW5nVG9rZW5pemVyKGluU3RyaW5n
LCAiICIsIHRydWUpOwoKCXdoaWxlIChzdGtuenIuaGFzTW9yZUVsZW1lbnRzKCkpewoJCXRva2Vu
ID0gc3RrbnpyLm5leHRUb2tlbigpOwoJCWlmICh0b2tlbi5lcXVhbHNJZ25vcmVDYXNlKCIgIikp
ewoJCQlvdXRTdHJpbmcgKz0gIiAiOwoJCX1lbHNlewogICAgCSAgICB0ZW1wdG9rZW4gPSB0b2tl
bi5zdWJzdHJpbmcoMCwxKTsKCSAgICAJdGVtcHRva2VuID0gdGVtcHRva2VuLnRvVXBwZXJDYXNl
KCk7CgkJCXRlbXB0b2tlbiArPSAodG9rZW4uc3Vic3RyaW5nKDEsdG9rZW4ubGVuZ3RoKCkpKS50
b0xvd2VyQ2FzZSgpOwoJCQlvdXRTdHJpbmcgKz0gdGVtcHRva2VuOwoJCX0vL2VuZCBvZiBpZgoJ
fS8vZW5kIG9mIHdoaWxlCn0vL2VuZCBvZiBpZgoKb3V0U3RyaW5nID0gb3V0U3RyaW5nLnRyaW0o
KTsKCgovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJvdXRTdHJpbmci
LCBvdXRTdHJpbmcgKTsKcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7Cg==</value>
</Values>
