<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeAllLeadingZeroes</value>
  <value name="encodeutf8">true</value>
  <value name="body">IC8qCglSZW1vdmluZyBMZWFkaW5nIFplcm9zIGZyb20gQWxwaGFudW1lcmljIFN0cmluZyBVdGls
aXR5CglBdXRob3I6ICBDcm93ZSBDaGl6ZWsKCURhdGU6ICAgIDEyLzE2LzAzCgktIElmIHRoZSBp
bnB1dCBzdHJpbmcgaXMgbnVsbCB0aGVuIHJldHVybnMgbnVsbAoJLSBFbHNlIHJlbW92ZXMgYWxs
IHRoZSBsZWFkaW5nIHplcm9zLgoqLyAKLy8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVD
dXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nCWluU3RyaW5nID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpblN0cmluZyIgKTsKCmNoYXIgYzsKaW50IGNv
dW50ID0gMDsKaW50IHN0ckxlbmd0aCA9IDA7IC8vaW5TdHJpbmcubGVuZ3RoKCk7ClN0cmluZyBv
dXRTdHJpbmcgOwoKaWYoaW5TdHJpbmcgPT0gbnVsbCl7CglvdXRTdHJpbmcgPSBudWxsOwp9CmVs
c2UgewoJc3RyTGVuZ3RoID0gaW5TdHJpbmcubGVuZ3RoKCk7Cglmb3IoaW50IGk9MDsgaSA8IGlu
U3RyaW5nLmxlbmd0aCgpOyBpKyspewoJCWMgPSBpblN0cmluZy5jaGFyQXQoaSk7CiAgICAJaWYo
YyA9PSAnMCcpewogICAgCWNvdW50Kys7CiAgICAJfQogICAgCWVsc2V7CiAgICAJCWJyZWFrOwog
ICAgCX0KCX0KCS8vc3RyID0gbmV3IEludGVnZXIoY291bnQpLnRvU3RyaW5nKCk7CglvdXRTdHJp
bmcgPSBpblN0cmluZy5zdWJzdHJpbmcoY291bnQsc3RyTGVuZ3RoKTsKfQoKCnBpcGVsaW5lQ3Vy
c29yLmluc2VydEFmdGVyKCJvdXRTdHJpbmciLCBvdXRTdHJpbmcpOwpwaXBlbGluZUN1cnNvci5k
ZXN0cm95KCk7</value>
</Values>
